#!/usr/bin/env bash
# Claim the iGPU for vfio-pci at boot, so amdgpu never touches it.
#
# WHY THIS IS THE FIX
#
# The guest cannot start the GPU's command processor, and the reason is not anything about
# Apple's driver. On GFX10 a microengine fetches its microcode through an instruction cache
# whose base address lives in CP_CPC_IC_BASE_LO/HI, and after the host's amdgpu has had the
# device those registers hold amdgpu's own addresses:
#
#     CP_CPC_IC_BASE = 0x8_5f904000    CP_PFP_IC_BASE = 0x8_5f87c000
#     CP_ME_IC_BASE  = 0x8_5f8c0000
#
# The host's framebuffer offset is 0x840000000, so those are carveout addresses that meant
# something under the host's memory-controller layout and nothing under the guest's. They
# are also locked: writes are ignored through the framebuffer accessor, through TTL's own
# _gc_cgs_write_register_ext2, with GRBM_GFX_INDEX broadcasting, inside an RLC_SAFE_MODE
# request, and with both MECs halted -- while CP_MEC_CNTL and every GMC register in reach
# are writable. The PSP owns the addresses the CP fetches from for the life of the reset,
# and GFX_CMD_ID_AUTOLOAD_RLC, the command that would hand them back, answers
# TEE_ERROR_BUSY. Moving the guest's framebuffer aperture so the locked address lands on
# microcode the plugin writes and verifies by readback is not enough either: the
# instruction cache will not prime and the engines never execute.
#
# So do not let amdgpu have the device in the first place. Bound to vfio-pci from boot, the
# iGPU reaches the guest exactly as the system firmware left it -- the PSP has already
# autoloaded the graphics firmware and started the microengines, with addresses of its own
# choosing, which is the state a working driver expects to inherit.
#
# WHAT THIS CHANGES
#
#   /etc/modprobe.d/vfio-igpu.conf   binds 1002:13c0 to vfio-pci and orders it before amdgpu
#   /etc/mkinitcpio.conf             adds vfio-pci to MODULES, so it is present early enough
#   initramfs                        regenerated for the main kernel only
#
# The LTS kernel's initramfs is deliberately left alone, so its Limine entry remains a
# known-good fallback if anything goes wrong.
#
# SAFETY
#
# Only 1002:13c0 is claimed. The display runs on the discrete Navi 48 (1002:7550) and is
# untouched; the iGPU's IOMMU group 31 contains no other function, so nothing else moves
# with it. Reverting is: rm the modprobe.d file, undo the MODULES line, regenerate.
#
# Requires a reboot to take effect, and does nothing until then.
set -euo pipefail

IGPU_ID=1002:13c0
DGPU_ID=1002:7550
CONF=/etc/modprobe.d/vfio-igpu.conf
MKI=/etc/mkinitcpio.conf

[[ $EUID -eq 0 ]] || { echo "run me with sudo" >&2; exit 1; }

# Refuse to run if the ids are not what this script was written against -- claiming the
# wrong device would take the display with it.
lspci -nn | grep -q "\[${IGPU_ID}\]" || { echo "no ${IGPU_ID} present; aborting" >&2; exit 1; }
lspci -nn | grep -q "\[${DGPU_ID}\]" || {
    echo "the discrete GPU ${DGPU_ID} is not present -- refusing to hand over the only GPU" >&2
    exit 1; }

cat > "$CONF" <<EOF
# Generated by macos-vm/enable-early-vfio.sh
# Claim only the Raphael/Granite Ridge iGPU. The discrete Navi 48 (${DGPU_ID}) keeps amdgpu.
options vfio-pci ids=${IGPU_ID}
softdep amdgpu pre: vfio-pci
EOF
echo "wrote $CONF"

cp -a "$MKI" "${MKI}.pre-vfio"
if grep -qE '^MODULES=\(.*vfio_pci' "$MKI"; then
    echo "$MKI already lists vfio_pci"
else
    sed -i -E 's/^MODULES=\((.*)\)$/MODULES=(vfio_pci vfio vfio_iommu_type1 \1)/' "$MKI"
    echo "added vfio_pci to $MKI MODULES (backup at ${MKI}.pre-vfio)"
fi
grep -E '^MODULES' "$MKI"

# Main kernel only: the LTS initramfs stays as it is so its boot entry remains a fallback.
mkinitcpio -p linux-cachyos

cat <<'EOF'

Done. Reboot to activate.

After the reboot, check that it took:

    lspci -nnks 7b:00.0 | grep 'driver in use'      # expect vfio-pci
    dmesg | grep -c 'amdgpu 0000:7b:00.0'           # expect 0

Then gpu-bind.sh is no longer needed -- the device is already on vfio-pci -- and
./redeploy.sh can go straight ahead. What to look for in the guest is the microengines
actually running:

    tr -d '\r' < run/serial.log | grep -E 'XP: MEC2 instr|THE CP EXECUTES'

To revert: rm /etc/modprobe.d/vfio-igpu.conf, restore /etc/mkinitcpio.conf.pre-vfio,
mkinitcpio -p linux-cachyos, reboot.
EOF
