#!/usr/bin/env bash
# Claim the iGPU for vfio-pci at boot, so amdgpu never touches it.
#
# DO NOT RUN THIS. IT IS KEPT AS A RECORD OF A REFUTED IDEA.
#
# The premise was that the CP instruction-cache bases hold the HOST amdgpu's addresses:
#
#     CP_CPC_IC_BASE = 0x8_5f904000    CP_PFP_IC_BASE = 0x8_5f87c000
#     CP_ME_IC_BASE  = 0x8_5f8c0000
#
# and that if amdgpu were never allowed to bind the device, the guest would inherit it as
# the system firmware left it, with the microengines already running on addresses of the
# firmware's choosing.
#
# The experiment was run. It cost two host hard-hangs -- 53 seconds into the first launch,
# then ~74 seconds into the first launch after a reboot -- and it disproved its own premise.
# With amdgpu confirmed never to have bound the device this boot ("journalctl -k -b | grep
# -c 'amdgpu 0000:7b:00.0'" == 0), the plugin's own pre-TTL report shows the registers start
# at ZERO and acquire those values during the GUEST's initialisation:
#
#     XR: pre-TTL: IC bases CPC=0_00000000   cntl=0x10 op=0   | PFP=0_00000000   | ME=0_00000000
#     XR: pre-TTL: IC bases CPC=0x8_5f904000 cntl=0x10 op=0x2 | PFP=0x8_5f87c000 | ME=0x8_5f8c0000
#
# So those addresses were never amdgpu residue. The guest's own PSP writes them during
# firmware autoload, and it writes HOST-PHYSICAL addresses, because the PSP runs against the
# real memory map: 0x8_5f904000 is the host's framebuffer carveout base 0x840000000 plus
# 0x1f904000, i.e. 505 MB into a 512 MB carveout -- exactly where firmware parks CP
# microcode. Keeping amdgpu away from the device cannot change any of that, and the guest
# reaches the same state either way.
#
# WHAT THE REAL PROBLEM TURNED OUT TO BE
#
# The CP dereferences that register as an MC address, through a GMC that Apple's driver has
# programmed for the guest's BAR0 window:
#
#     GCMC_VM_FB_LOCATION_BASE = 0xf400000000     GCMC_VM_FB_OFFSET = 0x840000000
#     MC -> phys = MC - BASE + OFFSET
#
# Treat 0x8_5f904000 as an MC address under that mapping and it resolves to
# 0xff1c9f904000, which is nowhere. The MC address that would reach the PSP's microcode is
# 0xf41f904000. So the microengines never execute not because the addresses are stale, but
# because BASE != OFFSET: every physical address the PSP programmed is unreachable through
# the guest's own aperture. See findings/GPU-RE.md.
#
# This script is left in place, disabled, because the reasoning above is only legible next
# to the thing it refutes. To read what it used to do, see git history.

set -euo pipefail

cat >&2 <<'REFUSED'
enable-early-vfio.sh is disabled on purpose.

Its premise -- that the CP instruction-cache bases hold the host amdgpu's addresses -- was
disproved by running it. On a device amdgpu never bound, those registers start at zero and
the guest's own PSP writes them. The experiment cost two host hard-hangs and changed
nothing about how far the guest gets.

If you have a new reason to want the iGPU on vfio-pci from boot, write it in the header
first, then delete this block. Read the comment above before you do.
REFUSED
exit 1

IGPU_ID=1002:13c0
IAUD_ID=1002:1640      # the iGPU's own HDMI/DP audio function, 7b:00.1
DGPU_ID=1002:7550
CONF=/etc/modprobe.d/vfio-igpu.conf
MKI=/etc/mkinitcpio.conf

[[ $EUID -eq 0 ]] || { echo "run me with sudo" >&2; exit 1; }

# Refuse to run if the ids are not what this script was written against -- claiming the
# wrong device would take the display with it.
#
# Uses lspci's own -d filter and a plain string test rather than "lspci -nn | grep -q":
# that pipeline reported a false negative for the discrete GPU on the first real run, and a
# guard that can fail for reasons unrelated to what it is guarding is worse than no guard.
# -d needs no regex, no pipeline and no exit-status plumbing, and both ids are echoed so a
# future failure says what was actually seen.
igpu_seen="$(lspci -nn -d "$IGPU_ID" || true)"
dgpu_seen="$(lspci -nn -d "$DGPU_ID" || true)"
echo "iGPU (${IGPU_ID}): ${igpu_seen:-<not found>}"
echo "dGPU (${DGPU_ID}): ${dgpu_seen:-<not found>}"
[[ -n "$igpu_seen" ]] || { echo "no ${IGPU_ID} present; aborting" >&2; exit 1; }
[[ -n "$dgpu_seen" ]] || {
    echo "the discrete GPU ${DGPU_ID} is not present -- refusing to hand over the only GPU" >&2
    exit 1; }

cat > "$CONF" <<EOF
# Generated by macos-vm/enable-early-vfio.sh
# Claim the Raphael/Granite Ridge iGPU and its own audio function, and nothing else.
# The discrete Navi 48 (${DGPU_ID}) and its audio (1002:ab40) keep amdgpu and snd_hda_intel.
#
# Why the audio function is here too: 7b:00.1 is the iGPU's HDMI/DP audio block, and it
# shares the graphics core's reset and power domain. Leaving it on the host's
# snd_hda_intel means a host driver is actively holding a block that the guest resets and
# reinitialises underneath it -- a well-known way to hang the fabric on a multi-function
# GPU. Verified safe to take on this machine: /sys/class/sound/card1 is the DISCRETE GPU's
# audio (0000:03:00.1), which is the monitor's path and stays put, card2 was this function
# and was idle, and the default sink is a USB headset.
options vfio-pci ids=${IGPU_ID},${IAUD_ID}
softdep amdgpu pre: vfio-pci
softdep snd_hda_intel pre: vfio-pci
EOF
echo "wrote $CONF"

cp -a "$MKI" "${MKI}.pre-vfio"
if grep -qE '^MODULES=\(.*vfio_pci' "$MKI"; then
    echo "$MKI already lists vfio_pci"
else
    sed -i -E 's/^MODULES=\((.*)\)$/MODULES=(vfio_pci vfio vfio_iommu_type1 \1)/' "$MKI"
    echo "added vfio_pci to $MKI MODULES (backup at ${MKI}.pre-vfio)"
fi
grep -E '^MODULES' "$MKI"

# limine-mkinitcpio, NOT mkinitcpio -p.
#
# /boot/limine.conf pins every initramfs by blake2b hash:
#
#     module_path: boot():/<id>/linux-cachyos/initramfs#08ce46cf...
#
# so regenerating an image with plain mkinitcpio leaves the pinned hash stale and Limine
# refuses that entry at the next boot. limine-mkinitcpio -- which is
# "echo rebuild | /usr/share/libalpm/scripts/limine-mkinitcpio-install", the same script the
# pacman hook runs on a kernel update -- rebuilds the images and re-pins the hashes together,
# which is the only way to keep the two in step. It does all kernels rather than one, so the
# LTS image is rebuilt too; the fallback that matters is Limine's own limine_history entries,
# which keep the previous images and their hashes.
limine-mkinitcpio

cat <<'EOF'

Done. Reboot to activate.

After the reboot, check that it took:

    lspci -nnks 7b:00.0 | grep 'driver in use'      # expect vfio-pci
    dmesg | grep -c 'amdgpu 0000:7b:00.0'           # expect 0

Then gpu-bind.sh is no longer needed -- the device is already on vfio-pci -- and
./redeploy.sh can go straight ahead. What to look for in the guest is the microengines
actually running:

    tr -d '\r' < run/serial.log | grep -E 'XP: MEC2 instr|THE CP EXECUTES'

To revert: rm /etc/modprobe.d/vfio-igpu.conf, restore /etc/mkinitcpio.conf.pre-vfio,
mkinitcpio -p linux-cachyos, reboot.
EOF
