#!/usr/bin/env python3
"""Convert Raphael's DMCUB (DCN 3.1.5) firmware into src/DmcubFirmware.hpp.

Linux ships it as amdgpu/dcn_3_1_5_dmcub.bin: a 0x28-byte common firmware
header, 0xd8 bytes of padding, then the PSP-signed instruction image (its $PS1
header at +0x10). That image is exactly what AMD's HWLibs hands PSP for DCN 3.0
(`_atidmcub_instruction_dcn30`), so only the signed image is embedded.

    tools/gen-dmcub-firmware.py --source /usr/lib/firmware/amdgpu/dcn_3_1_5_dmcub.bin.zst
"""
import argparse
import hashlib
import json
import struct
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read_source(path):
    data = path.read_bytes()
    if path.suffix == '.zst':
        data = subprocess.run(['zstd', '-dc'], input=data, capture_output=True, check=True).stdout
    return data


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--source', type=Path,
                        default=Path('/usr/lib/firmware/amdgpu/dcn_3_1_5_dmcub.bin.zst'))
    parser.add_argument('--header', type=Path, default=ROOT / 'src/DmcubFirmware.hpp')
    parser.add_argument('--manifest', type=Path, default=ROOT / 'build-support/dmcub-firmware.json')
    args = parser.parse_args()

    compressed = args.source.read_bytes()
    data = read_source(args.source)
    (size, header_size, _, _, ip_major, ip_minor, version, ucode_size, ucode_offset, _,
     inst_const, bss_data) = struct.unpack_from('<IIHHHHIIIIII', data, 0)
    if size != len(data) or ucode_offset + ucode_size != len(data):
        raise SystemExit('unexpected firmware container layout')
    if (ip_major, ip_minor) != (3, 1) or inst_const != ucode_size or bss_data != 0:
        raise SystemExit('not a DCN 3.1 DMCUB image with instructions only')
    payload = data[ucode_offset:ucode_offset + ucode_size]
    if payload[0x10:0x14] != b'$PS1':
        raise SystemExit('payload lacks the PSP $PS1 header')

    lines = ['// AMD DMCUB firmware for DCN 3.1.5 (Raphael); see build-support/dmcub-firmware.json',
             '// and LICENSE.amdgpu. Generated by tools/gen-dmcub-firmware.py -- do not edit.',
             '#pragma once',
             '#include <stdint.h>',
             f'static constexpr uint32_t raphaelDmcubFirmwareVersion = {version:#010x};',
             'static const uint8_t raphaelDmcubFirmware[] = {']
    for i in range(0, len(payload), 24):
        lines.append(','.join(f'0x{b:02x}' for b in payload[i:i + 24]) + ',')
    lines.append('};')
    args.header.write_text('\n'.join(lines) + '\n')
    manifest = {
        'source': str(args.source),
        'linux_firmware_sha256': hashlib.sha256(compressed).hexdigest(),
        'payload_sha256': hashlib.sha256(payload).hexdigest(),
        'linux_outer_header_removed_bytes': ucode_offset,
        'payload_size': len(payload),
        'version': f'{version:#x}',
        'signed_amd_header_preserved': True,
        'hardware_status': 'untested',
    }
    args.manifest.write_text(json.dumps(manifest, indent=2) + '\n')
    print(json.dumps(manifest, indent=2))
    return 0


if __name__ == '__main__':
    sys.exit(main())
